<?php
/*
* Register custom Gutenberg blocks using Lazy Blocks plugin
*/

if ( function_exists( 'lazyblocks' ) ) :

    lazyblocks()->add_block( array(
        'id' => 835,
        'title' => 'Cartes avec icons',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z" /></svg>',
        'keywords' => array(
            0 => 'aplicaen',
            1 => ' liste',
            2 => ' icon',
        ),
        'slug' => 'lazyblock/icon-card-list',
        'description' => 'Afficher une liste de cartes avec des icons représentatifs.',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_149aa5474a' => array(
                'type' => 'text',
                'name' => 'section-title',
                'default' => '',
                'label' => 'Titre de la section',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_becb5c4bfd' => array(
                'type' => 'repeater',
                'name' => 'card-list',
                'default' => '',
                'label' => 'Liste de cartes',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
                'rows_label' => 'Carte {{#}}',
                'rows_add_button_label' => 'Ajouter une carte',
            ),
            'control_1f29844eec' => array(
                'type' => 'image',
                'name' => 'card-icon',
                'default' => '',
                'label' => 'Icon',
                'help' => 'Icon représentatif. De préférence en PNG.',
                'child_of' => 'control_becb5c4bfd',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_01bbe44bf9' => array(
                'type' => 'text',
                'name' => 'card-name',
                'default' => '',
                'label' => 'Titre',
                'help' => 'Titre de la carte',
                'child_of' => 'control_becb5c4bfd',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_1849064830' => array(
                'type' => 'rich_text',
                'name' => 'card-description',
                'default' => '',
                'label' => 'Description',
                'help' => 'Description de la carte',
                'child_of' => 'control_becb5c4bfd',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
                'multiline' => 'true',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'selected',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );

    lazyblocks()->add_block( array(
        'id' => 824,
        'title' => 'Cartes avec emoji',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm3.5-9c.83 0 1.5-.67 1.5-1.5S16.33 8 15.5 8 14 8.67 14 9.5s.67 1.5 1.5 1.5zm-7 0c.83 0 1.5-.67 1.5-1.5S9.33 8 8.5 8 7 8.67 7 9.5 7.67 11 8.5 11zm3.5 6.5c2.33 0 4.31-1.46 5.11-3.5H6.89c.8 2.04 2.78 3.5 5.11 3.5z" /></svg>',
        'keywords' => array(
            0 => 'aplicaen',
            1 => ' liste',
            2 => ' emoji',
        ),
        'slug' => 'lazyblock/emoji-card-list',
        'description' => 'Affiche une liste de cartes avec des emoji pour un aspect ludique. Copier-coller depuis annuaire emojis : https://emojipedia.org/',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_9f89d34894' => array(
                'type' => 'text',
                'name' => 'section-title',
                'default' => '',
                'label' => 'Titre de la section',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_06bbcf4ed7' => array(
                'type' => 'repeater',
                'name' => 'card-list',
                'default' => '',
                'label' => 'Liste de cartes',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
                'rows_label' => 'Carte {{#}}',
                'rows_add_button_label' => 'Ajouter une carte',
            ),
            'control_34da8048ad' => array(
                'type' => 'text',
                'name' => 'card-emoji',
                'default' => '',
                'label' => 'Emoji',
                'help' => 'Coller l\'emoji en tant que texte dans ce champ',
                'child_of' => 'control_06bbcf4ed7',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
                'choices' => array(
                ),
            ),
            'control_97f98a4790' => array(
                'type' => 'text',
                'name' => 'card-name',
                'default' => '',
                'label' => 'Titre',
                'help' => 'Titre de la carte',
                'child_of' => 'control_06bbcf4ed7',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fbd850481a' => array(
                'type' => 'rich_text',
                'name' => 'card-description',
                'default' => '',
                'label' => 'Description',
                'help' => 'Description de la carte',
                'child_of' => 'control_06bbcf4ed7',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
                'multiline' => 'true',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'selected',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );

    lazyblocks()->add_block( array(
        'id' => 802,
        'title' => 'Liste d\'étapes',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M2 17h2v.5H3v1h1v.5H2v1h3v-4H2v1zm1-9h1V4H2v1h1v3zm-1 3h1.8L2 13.1v.9h3v-1H3.2L5 10.9V10H2v1zm5-6v2h14V5H7zm0 14h14v-2H7v2zm0-6h14v-2H7v2z" /></svg>',
        'keywords' => array(
            0 => 'aplicaen',
            1 => ' étape',
            2 => 'liste',
        ),
        'slug' => 'lazyblock/steps-list',
        'description' => 'Affiche une liste d étapes sous forme de cartes numérotées.',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_e56bb041d1' => array(
                'type' => 'text',
                'name' => 'section-title',
                'default' => '',
                'label' => 'Titre de la section',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_f20a7940ef' => array(
                'type' => 'repeater',
                'name' => 'steps',
                'default' => '',
                'label' => 'Étapes',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
                'rows_label' => 'Étape {{#}}',
                'rows_add_button_label' => 'Ajouter une étape',
            ),
            'control_4e3a7943e1' => array(
                'type' => 'text',
                'name' => 'step-name',
                'default' => '',
                'label' => 'Titre',
                'help' => 'Titre de l\'étape',
                'child_of' => 'control_f20a7940ef',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_ef8b384a5f' => array(
                'type' => 'textarea',
                'name' => 'step-description',
                'default' => '',
                'label' => 'Description',
                'help' => 'Description courte de l\'étape.',
                'child_of' => 'control_f20a7940ef',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'selected',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );

    lazyblocks()->add_block( array(
        'id' => 791,
        'title' => 'Liste de prestations',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M4 14h4v-4H4v4zm0 5h4v-4H4v4zM4 9h4V5H4v4zm5 5h12v-4H9v4zm0 5h12v-4H9v4zM9 5v4h12V5H9z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/services-list',
        'description' => 'Affiche la liste des prestations associées à une expertise.',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_fb58924ffb' => array(
                'type' => 'text',
                'name' => 'section-title',
                'default' => '',
                'label' => 'Titre de la section',
                'help' => 'Titre à afficher avant la liste de prestations.',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_7e3b094853' => array(
                'type' => 'url',
                'name' => 'parent-page-url',
                'default' => '',
                'label' => 'Page parente',
                'help' => 'URL de la page de l Expertise pour laquelle afficher la liste des prestations.',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'selected',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );

    lazyblocks()->add_block( array(
        'id' => 781,
        'title' => 'Processus d\'étude',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3 13h8V3H3v10zm0 8h8v-6H3v6zm10 0h8V11h-8v10zm0-18v6h8V3h-8z" /></svg>',
        'keywords' => array(
            0 => 'aplicaen',
            1 => ' processus',
        ),
        'slug' => 'lazyblock/process',
        'description' => 'Insère une copie la section Notre processus de la page d accueil.',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );

    lazyblocks()->add_block( array(
        'id' => 763,
        'title' => 'Liste de membres',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z" /></svg>',
        'keywords' => array(
            0 => 'aplicaen',
            1 => ' carte',
            2 => ' membre',
        ),
        'slug' => 'lazyblock/member-list',
        'description' => 'Affichage d&#039;une liste des membres du mandat actuel.',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_9349824e30' => array(
                'type' => 'repeater',
                'name' => 'member-card',
                'default' => '',
                'label' => 'Cartes des membres',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'true',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
                'rows_add_button_label' => 'Ajouter une carte',
                'rows_label' => 'Membre {{#}}',
            ),
            'control_f98bf1487b' => array(
                'type' => 'image',
                'name' => 'member-picture',
                'default' => '',
                'label' => 'Photo',
                'help' => 'Photo du membre. Si champ vide, une photo par défaut sera affichée (logo d\'Aplicaen).',
                'child_of' => 'control_9349824e30',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_66faba4baf' => array(
                'type' => 'text',
                'name' => 'member-name',
                'default' => '',
                'label' => 'Nom',
                'help' => 'Nom complet du membre',
                'child_of' => 'control_9349824e30',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_b98a0d4b26' => array(
                'type' => 'text',
                'name' => 'member-position',
                'default' => '',
                'label' => 'Poste',
                'help' => 'Exemple : président, trésorier, etc.',
                'child_of' => 'control_9349824e30',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_2a095040a8' => array(
                'type' => 'email',
                'name' => 'member-email',
                'default' => '',
                'label' => 'Email',
                'help' => 'Adresse courriel du membre',
                'child_of' => 'control_9349824e30',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_a3aa3d4725' => array(
                'type' => 'url',
                'name' => 'member-linkedin',
                'default' => '',
                'label' => 'LinkedIn',
                'help' => 'URL du compte LinkedIn du membre',
                'child_of' => 'control_9349824e30',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'selected',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );

endif;

 ?>
